/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface User {
  created_at: Generated<string>;
  email: string;
  id: Generated<number>;
  password_hash: string;
  updated_at: Generated<string>;
}

export interface DB {
  user: User;
}
