import { Kysely, sql } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  // sql generated by `npx @better-auth/cli generate`
  await sql`
alter table "user" add column "role" text;
  `.execute(db);
  await sql`
  alter table "user" add column "banned" integer;
  `.execute(db);
  await sql`
alter table "user" add column "banReason" text;
  `.execute(db);
  await sql`
alter table "user" add column "banExpires" date;
  `.execute(db);
  await sql`
alter table "session" add column "impersonatedBy" text;
  `.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`
  alter table "user" drop column "role";
    `.execute(db);
    await sql`
    alter table "user" drop column "banned";
    `.execute(db);
    await sql`
  alter table "user" drop column "banReason";
    `.execute(db);
    await sql`
  alter table "user" drop column "banExpires";
    `.execute(db);
    await sql`
  alter table "session" drop column "impersonatedBy";
    `.execute(db);
}
