/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UploadTestIndexImport } from './routes/upload-test/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as SendHashImport } from './routes/send.$hash'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UploadTestIndexRoute = UploadTestIndexImport.update({
  id: '/upload-test/',
  path: '/upload-test/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const SendHashRoute = SendHashImport.update({
  id: '/send/$hash',
  path: '/send/$hash',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/send/$hash': {
      id: '/send/$hash'
      path: '/send/$hash'
      fullPath: '/send/$hash'
      preLoaderRoute: typeof SendHashImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/upload-test/': {
      id: '/upload-test/'
      path: '/upload-test'
      fullPath: '/upload-test'
      preLoaderRoute: typeof UploadTestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/send/$hash': typeof SendHashRoute
  '/profile': typeof ProfileIndexRoute
  '/upload-test': typeof UploadTestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/send/$hash': typeof SendHashRoute
  '/profile': typeof ProfileIndexRoute
  '/upload-test': typeof UploadTestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/send/$hash': typeof SendHashRoute
  '/profile/': typeof ProfileIndexRoute
  '/upload-test/': typeof UploadTestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/send/$hash' | '/profile' | '/upload-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/send/$hash' | '/profile' | '/upload-test'
  id: '__root__' | '/' | '/send/$hash' | '/profile/' | '/upload-test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SendHashRoute: typeof SendHashRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  UploadTestIndexRoute: typeof UploadTestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SendHashRoute: SendHashRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  UploadTestIndexRoute: UploadTestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/send/$hash",
        "/profile/",
        "/upload-test/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/send/$hash": {
      "filePath": "send.$hash.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/upload-test/": {
      "filePath": "upload-test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
